/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ufpa.physics;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Rectangle;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class App extends JFrame{
    private Component s;

    public App(){
        super("ELETROMAGNETISMO");
        s = new Simulation();
        this.setFocusable(true);
        this.requestFocusInWindow();
        this.add(s);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setMinimumSize(new Dimension(800, 800));
        this.setMinimumSize(new Dimension(800, 800));
        this.setResizable(false);
    }

    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            var a = new App();
            a.setVisible(true);
        });
    }
}
